### ISSUE TITLE
theme not working after installation

### ISSUE THREAD

**Issue by rick-dev-hub** [printempw/hexo-theme-murasaki#1]
I init a fresh hexo project via below command:
`
hexo init xx-blog
`
then follow installation guide in repo readme
First I encounter hexo-util not found , after pnpm i hexo-util, it disappears.
Then the project seems working with error below
`
ERROR Script load failed: themes/murasaki/scripts/lazyload.js
TypeError: Cannot read properties of undefined (reading 'lazyload')
`
and all css is lost and html content seems some variables.
is there any other thing I need to do?

repo here: https://github.com/rick-yao/hexo-example

**Comment by prinsss** [comment]
Sorry for that. I forgot to check against user's configuration when implementing image lazy-load feature.

Add this to your Hexo's `_config.yml` could help:

```yml
lazyload:
  enable: false
``` 

If you would like to leave image lazy-load feature enabled, here is an working [example](https://github.com/prinsss/prinsss.github.io/blob/source/_config.yml#L109).

**Comment by rick-dev-hub** [comment]
Thanks for your quick response , I will try this. I also found your blog repo , I'll also find intuition there.
